name: html_runner
description: A powerful HTML Runner
version: 1.6.7+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.3.0
  path_provider: ^2.1.5
  archive: ^4.0.7
  permission_handler: ^11.4.0
  fluttertoast: ^8.2.14
  file_picker: ^10.3.10   # ← UPDATED
  image_picker: ^1.2.0
  intl: ^0.20.2
  http: ^1.3.0
  open_file: ^3.5.10

flutter:
  uses-material-design: true
